### ISSUE TITLE
Add support for VS2022 ARM Extension

### ISSUE THREAD

**Issue by lable** [nanoframework/Home#1344]
### Description

Microsoft Visual Studio Professional 2022 (ARM 64 位) - Current
版本 17.6.5

### How to solve the problem

none

**Comment by Ellerbach** [comment]
Hi @lable there are few chances that you will see this extension appearing for ARM64 mainly because we have no way to test it and so far, you are the first one to request.
If you want to give it a try, you can clone the repository https://github.com/nanoframework/nf-Visual-Studio-extension and check if all is working, adjust what needs to be adjusted and submit a PR! Follow the instructions on how to debug an extension, you should be able to do it as well in ARM64.

**Comment by lable** [comment]
Hi @Ellerbach PR is commit，but debuger is not work.

![Xnip2023-08-19_11-09-40](https://github.com/nanoframework/Home/assets/172791/c5623d6f-7d43-4b71-b230-58afd396ddfd)

**Comment by Ellerbach** [comment]
You have to clone the repository, install the Visual Studio extension tools for Visual Studio, open the solution and hit F5 to see if that's working or not.

**Comment by lable** [comment]
> You have to clone the repository, install the Visual Studio extension tools for Visual Studio, open the solution and hit F5 to see if that's working or not.

Try to run it your way and still report the same error. Can I set breakpoints at that point in the code?

**Comment by Ellerbach** [comment]
> Try to run it your way and still report the same error. Can I set breakpoints at that point in the code?

I guess yes. @josesimoes to confirm!

**Comment by josesimoes** [comment]
Don't know to which breakpoints you're refering to. If that's on the extension code, then yes, you can set them wherever you want.

**Comment by josesimoes** [comment]
Nothing new on this issue.
As reported above, there are no plans for an ARM extension.
