### ISSUE TITLE
DateTime.UtcNow does not work anymore

### ISSUE THREAD

**Issue by MikroBusNet** [nanoframework/Home#271]
## Details about Problem

DateTime.UtcNow throws an _unsupported exception_

Worked before?  Yes
If so, with which nanoFrameowrk version: before separating System.DateTime, to me.

## Detailed repro steps so we can see the same problem
See screenshot below.

### Screenshot (if applicable/relevant)
![screenshot 210](https://user-images.githubusercontent.com/8463870/34471443-3d02c7ee-ef4a-11e7-9394-8416d3b309c9.JPG)

**Comment by josesimoes** [comment]
`DateTime.UtcNow` is working again.

Fixed by [16d4a8a](https://github.com/nanoframework/lib-nanoFramework.Runtime.Native/commit/16d4a8aecbd39e2f42ac4f0de54ad6a90b8548d6) and [c57666c](https://github.com/nanoframework/nf-interpreter/commit/c57666c37eb9602f137edfae552204d6097b63e4).

Checked against RTC sample.
