### ISSUE TITLE
Exception with event on GpioPin input type

### ISSUE THREAD

**Issue by MikroBusNet** [nanoframework/Home#272]
## Details about Problem
When a pin is declared as "Input", nf is throwing an exception when you try to add an event handler on the _ValueChanged_ event property.

Tested on F429 and Quail.

### Sample Project (if applicable)
```
public static void Main()
        {
            Thread.Sleep(1000);
            Console.WriteLine("Program started");

            var pin = GpioController.GetDefault().OpenPin(6 * 16 + 5); // PG5 on F429iDiscovery
            pin.SetDriveMode(GpioPinDriveMode.Input);
            pin.ValueChanged += Pin_ValueChanged; // Exception thrown here

            while (true)
            {
                Thread.Sleep(200);
            }
        }

        private static void Pin_ValueChanged(Object sender, GpioPinValueChangedEventArgs e)
        {
            Console.WriteLine("Pin changed, edge : " + e.Edge);
        }
```

### Screenshot (if applicable/relevant)
![screenshot 213](https://user-images.githubusercontent.com/8463870/34641003-9d1c1ae8-f2fd-11e7-8104-6c0c95b98bfa.JPG)

![image](https://user-images.githubusercontent.com/8463870/34641043-10c23a7c-f2fe-11e7-849a-87b9abab6d1e.png)

**Comment by josesimoes** [comment]
This is occurring because the GPIO pin object scope is main().
That's OK if you don't use it elsewhere.

As soon as you setup an event handler, _that_ event handler needs to be able to access the Gpio object from outside main. The scope need to be global _and_ static thus the Gpio object has to be declared outside main _and_ static.

Check the Gpio sample [here](https://github.com/nanoframework/Samples/tree/master/Gpio%2BEvents).
