### ISSUE TITLE
Add posisbility for build folder & clean before build

### ISSUE THREAD

**Issue by piwi1263** [nanoframework/Home#273]
Additional and optional setting in,  best would be cmake-variant.json for building output folder. In this case it is possible to keep you build for board-one, have to stop for some reaon but don't want to loose the build details for later use, switch to another board-two and do a build without have to erase the build folder of the previous build for board-one.

Another feature could be a FORCE_BUILD_CLEAN = TRUE | FALSE option in the same cmake-variant to kind of automagically cleanup up the actualy build folder before doing a new build. 

Currently the build handling has to be managed manually, which is doable but time consuming.

**Comment by josesimoes** [comment]
There is no simple answer for this... The truth is that a folder becomes _the_ build folder as soon as you launch CMake from it. Because everything in the CMake scripts is _relative_ it work fine from any folder.

If you check the documentation [here](https://github.com/nanoframework/Home/blob/master/docs/building/build-instructions.md#building-from-the-command-prompt) it explans exactly that: you go to *your* build folder and launch CMake from there. So you can have any number of build folders at any time. This is using the command prompt, of course. Using the CMake Tools in VS Code is a bit different because there are some complications associated with managing this. Check the following, for example:
vector-of-bool/vscode-cmake-tools#195
vector-of-bool/vscode-cmake-tools#206

With what's available today from the tools there is no way to handle this from the build scripts in order to accomplish that. The best option right now is to call CMake from the command prompt (but you'll have to adjust the launch paths accordingly).

About the same with "clean before build" see [here](http://cmake.3232098.n2.nabble.com/How-clean-generated-build-system-files-td7582278.html) or [here](https://stackoverflow.com/questions/9680420/looking-for-a-cmake-clean-command-to-clear-up-cmake-output). This would require CMake to know more about how the underlying build tool works (Ninja, msbuild, ...) 
Wrapping it up: this something that is external to the build _per se_ you have to clear the build folder with a script or, at least, delete CMakeCache.txt file from the build folder.
