### ISSUE TITLE
Program is starting before debugger takes control

### ISSUE THREAD

**Issue by MikroBusNet** [nanoframework/Home#314]
## Details about Problem

When you launch a debug session, the program is first run without debugging, then the debugger is attaching and restart the application.
But in the meantime, some code has already been executed in the program. Which could be inconvenient.

VS Extension : 0.3.8.57

## Detailed repro steps so we can see the same problem
Using the following code on a Quail board, when you launch the debug session, you will see that the green led is lit while the debugger is attaching, meaning that the program has already started.

The program then restarts as expected and the debug session starts as well.

### Sample Project (if applicable)
```
using System;
using System.Threading;
using Windows.Devices.Gpio;

namespace NFApp28
{
    public class Program
    {
        private static GpioPin _greenLED;
        private static GpioPin _redLED;

        public static void Main()
        {
            try
            {
                var gpioController = GpioController.GetDefault();

                _greenLED = gpioController.OpenPin(PinNumber('E', 15));
                _redLED = gpioController.OpenPin(PinNumber('C', 3));

                _greenLED.SetDriveMode(GpioPinDriveMode.Output);
                _redLED.SetDriveMode(GpioPinDriveMode.Output);

                _greenLED.Write(GpioPinValue.High);
                Thread.Sleep(2000);
                _greenLED.Write(GpioPinValue.Low);
                _redLED.Write(GpioPinValue.High);

                Thread.Sleep(2000);
                _redLED.Write(GpioPinValue.Low);
            }
            catch (Exception ex)
            {
                // Do whatever please you with the exception caught
            }
            finally
            {
                while (true)
                {
                    Thread.Sleep(100);
                }
            }
        }

        private static int PinNumber(char port, byte pin)
        {
            if (port < 'A' || port > 'J') throw new ArgumentException();

            return ((port - 'A') * 16) + pin;
        }
    }
}
```

**Comment by josesimoes** [comment]
This occurs because it was request some ago that the device should reboot and execute after a deployment happens. It was a passionate discussion and the motivation was that is was "stupid" having to manually reset the device after the deployment.

What you are describing above does happen because the operations inside VS happen in a sequence. When you start a debug session the first step is to *deploy* the application and required assemblies. Because of the above the CLR is reset and the app starts. The next step is to attach the debugger engine and start executing the app from the beginning. A new CLR reset has to happen for that to occur.

It's easy to understand that that initial execution (between the deploy and the debugging start) even being just the start of the app, can cause issues because the board is busy instead of just starting from an halt.

The only remedy here (at least that I can see) is to follow the _standard_ and prescribed procedure of deploying *without* resetting the target.

**Comment by piwi1263** [comment]
Assuming that depoy != debug and detectable in the extension. Why not react upon that and have different scenarios?

1.   Debug -> Do deploy logic -> do your debug thing
2.   Deploy -> Do deploy logic -> do reset

Is that not possible/doable?

**Comment by josesimoes** [comment]
Sorry but not possible...
This is the workflow in VS. The steps are fixed.
Deploy is the only one that can be tapped and used independently. For obvious reasons.

**Comment by MikroBusNet** [comment]
Then the good old _Thread.Sleep(1000);_ at the beginning of a program is still applicable to avoid such situation.
This will not prevent the program from running but will give some more time for debugger to restart/attach.

**Comment by josesimoes** [comment]
As there were no further contributions to this and @MikroBusNet has provided a workaround for those having issues with this behaviour, I'm closing this issue.
