### ISSUE TITLE
Cleanup warning on VS extension project build

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#369]
Right there are a bunch of warnings there that should be removed/fixed/assumed.

**Comment by steffalk** [comment]
![screenshot of first exception](https://user-images.githubusercontent.com/23035372/43128814-33f022da-8f33-11e8-91ce-22af96558ec8.png)
This is the first exception. It occurs because the UI actually does not show a device as long as it has not finished booting yet. The exception handler then just will cause the very same exception to reoccur. Then, a more global exception handler with a fully empty catch {} block hides all this from the user, which is suboptimal at least.
