### ISSUE TITLE
IoT GPIO, I2C, PWM, SPI ...

### ISSUE THREAD

**Issue by grahamehorner** [nanoframework/Home#441]
IMHO the nanoframework should follow the API created by the core CLR/FX for IoT see: https://github.com/dotnet/iot this would allow developers to prototype/debug using
hardware such as the RaspberryPI and/or share code between different OS and hardware
platforms.

**Comment by josesimoes** [comment]
Hi @grahamehorner!

I've compared the GPIO and SPI classes and I believe we overlap each other on most of it and are pretty close on the other... This must be because we are following the UWP API and I believe they are doing pretty much the same. 

Anything in particular that we are deviating too much from the original?

PS: wasn't aware of this project, thanks for the heads up 👍

**Comment by grahamehorner** [comment]
@josesimoes It would IMHO be great to align the namespaces and structure with possibly a wrapper to transform to newer style api in .net core into that which was exposed in the microframework, thus allowing development to move forward in terms of newer .net core standards while also providing support for the older framework.

**Comment by josesimoes** [comment]
We are in a good shape to do that (because of the overlap and similarities).
As they state on their repo, the API is most likely changing. We are better waiting for a stable version and then move into making the required changes. 

We the current limited resources it makes no sense keeping up with their changes. Unless, of course, someone is willing to take care of this. It's not that hard, actually... 😉

**Comment by grahamehorner** [comment]
@josesimoes I'm happy to do this; IMHO I think the view that this would bring out weighs any pain that maybe experienced with the changing API surface.

**Comment by josesimoes** [comment]
Understood. Let's open the discussion about this in [Discord#General](https://discord.gg/gCyBu8T) and ask the community about this.

**Comment by josesimoes** [comment]
@grahamehorner not much feedback from the community about this. Nevertheless this looks like the path to follow. 

Are you still interested in helping out? If yes we can start a POC for GPIO has it shouldn't be that complicated and we'll see here that takes us.

**Comment by josesimoes** [comment]
I've filled an issue on the dotnet/iot repo proposing an improvement (which nanoframework already has 😉 🚀 ) provide a Toggle() method for Gpio pins. 

Check [here](https://github.com/dotnet/iot/issues/107).

**Comment by grahamehorner** [comment]
@josesimoes definitely, also looking at some kind of system where you can create Virtual/simulated electronic circuit that are connected to the GPIO, PWM, drivers.

**Comment by grahamehorner** [comment]
@josesimoes would you like to DM me would love to have a repo to play/discuss possible ELL or NELL project here.

Cheers
Grahame

**Comment by josesimoes** [comment]
@grahamehorner just pinged you on Discord

**Comment by grahamehorner** [comment]
Ok, unfortunately the hospital WiFi firewall is blocking 😩

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by josesimoes** [comment]
Any update on this matter? If not, I'll close the issue and it can be reopened at any time.

**Comment by josesimoes** [comment]
Seems that there are no updates. Closing issue.
