### ISSUE TITLE
SslStream.AuthenticateAsClient throws an exception

### ISSUE THREAD

**Issue by RoSchmiSec** [nanoframework/Home#472]
This method throws exception with many used certificates
As an example the site: -www.nanoframework.net did not work.

**Comment by josesimoes** [comment]
This behaviour is (was) caused by a short CRT heap that was preventing the authentication step from completing successfully.


After increasing the CRT heap on the ST_NUCLEO144_F746ZG community target all SSL samples now run as expected.


Tested with SSL sample  nanoframework/Samples/commit/d1a299c01213f4180901e6f2597f1b686839538b.
