### ISSUE TITLE
M2Mqtt cannot parse hostname

### ISSUE THREAD

**Issue by networkfusion** [nanoframework/Home#502]
## Details about Problem

**nanoFramework area:** (C# code | Nuget packages )

**VS version:**
VS2019 (latest)

**VS extension version:**
Latest

**Target:**
STM32F769I

**Firmware image version:**
Latest

## Description
When using the following code, an internal exception occurs:
```
string iotBrokerAddress = "<endpoint>.azure-devices.net"
MqttClient mqttc = new MqttClient(iotBrokerAddress, 8883, true, null, null, MqttSslProtocols.TLSv1_2);
```
This method worked fine in NetMF, so I expect it is a change in nF.

As a work around, the following can be used (although the method is marked as obsolete)
```
string iotBrokerAddress = "<endpoint>.azure-devices.net"
// get host entry
IPHostEntry hostEntry = Dns.GetHostEntry(iotBrokerAddress);
//parse by IP
MqttClient mqttc = new MqttClient(hostEntry.AddressList[0], 8883, true, null, null, MqttSslProtocols.TLSv1_2);
```

**Comment by josesimoes** [comment]
Can't see `iotBrokerAddress` declaration on your 1st block of code.

**Comment by networkfusion** [comment]
Sorry, coding in the issue leads to mistakes... Edited...

**Comment by networkfusion** [comment]
The issue is with `MQTTNetworkChannel` line `86` (`                remoteIpAddress = IPAddress.Parse(remoteHostName);`)

**Comment by josesimoes** [comment]
The exception you're seeing in VS output is expected. It's a empty catch block in `MqttNetworkChannel(...)` constructor when it's trying to use the host name "as is" testing if an IP address was supplied.

![image](https://user-images.githubusercontent.com/1881520/61142809-957e2f00-a4c8-11e9-8db3-a130d9b4e174.png)


Because nanoFramework is really awesome this is not required anymore and the correct approach can be DNS_ing_ whatever is in the host name. If it's a name, it will be resolved. If it's an IP, it will be resolved directly as an IP address.

I'll submit a change with this improvement.
