### ISSUE TITLE
Improve/add documentation for STM32F429I firmware management

### ISSUE THREAD

**Issue by edleno2** [nanoframework/Home#754]
### Details about Problem
Recent experience with setting up a STM32F429I-Discovery led to three problems that may not be documented:
1. WireProtocol uses the host USB connector (labeled "USB User" on device) for WireProtocol.  Device Explorer can't discover this device unless both USB cables are plugged in - mini-USB for power,  micro-USB for WireProtocol.  
2. STLink GUI may not install in all versions of Windows 10.   STM has replaced STLink GUI with STM32CubeProgrammer.  Create new link/document with screen shots of how to flash firmware (first time) using cube programmer.
3. Nanoff can fail to load firmware because ST-Link_CLI.exe can not load MSVCR0100.DLL (older C++ runtime dll).  Document the effect of not having this installed, include links to the MS install package for it.  Check if in nanoff the CLI will return a non-zero return code that we could detect and warn that ST-Link_CLI.exe has failed.

**nanoFramework area:** ( Visual Studio extension - Device Explorer and nanoFirmwareFlasher and Getting Started Guides )

**VS version:**

**VS extension version:**

**Target:**

**Firmware image version:**

### Description
Update documentation and code to improve experience of first time STM32F4 users with information specific to that chip and board set.

**Comment by josesimoes** [comment]
On 1. above: so you know this board, despite being "another" in the F4 series, was kept as a reference target precisely because of that second USB connector. This is the only STM32 board that has the user USB connector exposed (the STM32F769 has it, but it's using an USB PHY) thus we wanted to show how it works using the USB peripheral to expose the board as a CDC device. Unlike the others that use the UART and tunnel that through the composite USB device in ST-Link connector.
