### ISSUE TITLE
System.Device.Spi SpiDevice.GetBusInfo works with any busid!

### ISSUE THREAD

**Issue by AlirezaP** [nanoframework/Home#966]
### Library/API/IoT binding

System.Device.Spi

### Visual Studio version

VS2019

### Target name(s)

ALL TARGETS

### Description

hi
SpiDevice.GetBusInfo works always with any busid value!!!

for Example:

SpiDevice.GetBusInfo(1);
Output:
ChipSelectLineCount: 3
MaxClockFrequency: 40000000
MinClockFrequency: 78125
SupportedDataBitLengths: 
  8
  16
----------------------------
SpiDevice.GetBusInfo(100);
Output:
ChipSelectLineCount: 3
MaxClockFrequency: 40000000
MinClockFrequency: 78125
SupportedDataBitLengths: 
  8
  16
-------------------------
SpiDevice.GetBusInfo(x);
Output:
ChipSelectLineCount: 3
MaxClockFrequency: 40000000
MinClockFrequency: 78125
SupportedDataBitLengths: 
  8
  16
-------------------------

it seems busid to be ignored.

### Sample project or code

  SpiBusInfo spiBusInfo = SpiDevice.GetBusInfo(1);
  SpiBusInfo spiBusInfo = SpiDevice.GetBusInfo(10);
  SpiBusInfo spiBusInfo = SpiDevice.GetBusInfo(100);

**Comment by josesimoes** [comment]
Confirmed: there is no proper validation on the controller ID. 

Another thing worth pointing out is that actually, SpiBusInfo is still "looking" as the [UWP version](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Spi.SpiBusInfo?view=winrt-22000) instead of the [IoT version](https://docs.microsoft.com/en-us/dotnet/api/system.device.spi.spibusinfo?view=iot-dotnet-1.5).

Need to clarify the above before work is done on this.

**Comment by AlirezaP** [comment]
yes i used nanoFramework.System.Device.Gpio ([IOT Version](https://github.com/nanoframework/System.Device.Gpio))
